import React from 'react';
import './Livro.css'

function Livro() {
    return (
        <div className="livro__container">
            <div className="livro__row">
                <h1 className="livro__title">Pequena Biografia de Brígida Figueira</h1>
                <h2 className="livro__subtitle">Traduzida do Francês pelo Padre Oscar Figueira de Aquino</h2>
            </div>
            <div className="livro__row">
                <p className="livro__text">Aos bondosos Tios</p>
                <p className="livro__text">Chiquinho e Nhánhá</p>
                <p className="livro__text">oferece o grato sobrinho</p>
                <p className="livro__text">Pe. Oscar Figueira de Aquino</p>
                <p className="livro__text">Caraça, 2-11-33.</p>
                <hr/>
                <p className="livro__text">À memória de Bidinha</p>
                <p className="livro__text">Consummatus in brevi, explevit tempora multa.</p>
                <p className="livro__text">(Liv da sabedoria)</p>
                <p className="livro__text">Adormecida na flôr da idade, sua vida foi longa em atos de virtudes.</p>
                <hr/>

                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>

                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>

                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>

                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>
            </div>
            <div className="livro__row">
                <p className="livro__subsubtitle">Tipografia "Vozes de Petrópolis",</p>
                <p className="livro__subsubtitle">Petrópolis</p>
            </div>
        </div>
    );
}

export default Livro;