import React from 'react';
import './Livro.css'

function Livro() {
    return (
        <div className="livro__container">
            <div className="livro__row">
                <h1 className="livro__title">Pequena Biografia de Brígida Figueira</h1>
                <h2 className="livro__subtitle">Traduzida do Francês pelo Padre Oscar Figueira de Aquino</h2>
            </div>
            <div className="livro__row">
                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus blanditiis cumque doloremque dolores earum facere inventore iusto. Consequuntur cum eaque itaque ullam voluptatem! Adipisci alias commodi corporis dolor ducimus eaque earum et expedita, facere fugit illo iure laudantium natus nisi non obcaecati, officiis perspiciatis, porro quam qui quia quod repellat saepe sapiente temporibus tenetur voluptate. Architecto dolorum error et in neque omnis optio, quia quos recusandae, sint tempora tenetur veritatis? Alias beatae cupiditate ducimus, eaque fugiat libero maxime nisi nostrum quasi reiciendis rerum sequi similique, sunt, ullam velit vero voluptate! Aliquam, deserunt esse est eveniet laborum odio odit recusandae? Eum fuga maxime natus praesentium suscipit! Eos error ex ipsum saepe temporibus! Accusantium, at blanditiis ipsa itaque molestiae necessitatibus nihil non, nostrum optio porro quam quia, recusandae sed sequi similique? Adipisci alias aut blanditiis commodi consequuntur dolor, eius excepturi exercitationem ipsa, itaque maxime perferendis porro quas quibusdam quisquam quos repellat soluta. Adipisci commodi error impedit nemo nulla omnis optio saepe vero? Commodi ducimus nostrum numquam quo. Beatae consectetur consequatur distinctio doloribus maiores perspiciatis rem! Architecto consectetur ducimus eius eum incidunt nihil sapiente. Culpa dolore earum suscipit. Consequuntur deserunt eius eum, eveniet expedita, facilis hic laborum minima numquam quidem quo repudiandae, sapiente suscipit ut velit? Exercitationem laudantium modi quisquam sunt. Nobis, sequi, vel. Atque deleniti fugiat ipsa maiores mollitia neque numquam. Doloribus hic repellat rerum velit? Asperiores deserunt ducimus hic iste, maiores nisi quo reiciendis temporibus voluptates. Alias aliquid ea eos et iste iure omnis reprehenderit rerum totam! Doloribus ducimus eveniet expedita facere fuga molestias quos similique soluta tenetur. Asperiores aut, dolorum enim est eum ex facilis laudantium minus officiis quae quia rerum sequi sint sit soluta voluptate voluptatum. Aspernatur assumenda commodi delectus dolorum error fuga fugiat id saepe? Assumenda distinctio dolore dolorem dolorum ducimus eos ipsum nemo officia quisquam suscipit!</p>
                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>
                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>
                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>
                <p className="livro__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque delectus ducimus, enim facilis fugit in itaque iusto minima natus, quam reiciendis repellendus unde, veritatis voluptate! Assumenda dolores error ex excepturi fugit illo ipsam labore modi nisi quos, reprehenderit repudiandae saepe voluptates. Distinctio excepturi explicabo hic necessitatibus neque provident quam quisquam quos repellendus soluta? Corporis dignissimos doloribus nam officia quod voluptate, voluptatem. Aliquid animi architecto asperiores autem blanditiis consequatur cum earum error eveniet ex harum id iure iusto laboriosam libero maiores maxime, minima molestias, nesciunt non officia officiis optio quibusdam quod repellendus repudiandae sapiente vitae. Dolorum maiores nesciunt omnis sequi veniam voluptatem. Aperiam atque dolore dolorem earum illum impedit iste magnam optio sed vitae. Beatae ex incidunt ipsam perferendis porro temporibus velit vero vitae voluptatem. Asperiores atque delectus deleniti dolorum illo incidunt inventore iusto labore officiis, perspiciatis placeat quas sequi. A alias aliquid amet aperiam atque deleniti dicta dolor eos error est eum harum impedit incidunt iure libero nam, non nostrum, nulla officiis pariatur possimus praesentium quas, quis repudiandae saepe sit soluta. Aliquam amet architecto aspernatur at, beatae cupiditate delectus doloremque ducimus eligendi eos facilis fugiat hic ipsam ipsum iusto labore laudantium maxime mollitia nemo nihil perspiciatis quos sapiente suscipit tenetur ullam voluptas voluptatum. Aliquam consequatur deleniti distinctio dolorem eius exercitationem facere hic incidunt inventore iure iusto laborum nam nobis nostrum odio possimus quae qui quisquam, suscipit velit? Aliquam dicta illum ipsam modi. Beatae consectetur, debitis ipsam labore nobis nulla praesentium veniam. Cupiditate ipsum necessitatibus odit omnis possimus reprehenderit soluta.</p>
            </div>
            <div className="livro__row">
                <p className="livro__subsubtitle">Tipografia "Vozes de Petrópolis",</p>
                <p className="livro__subsubtitle">Petrópolis</p>
            </div>
        </div>
    );
}

export default Livro;